/* EDU-NETCRAKCER GROUP1 DDL SCRIPT */
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('smillions0', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'daslott0@globo.com', '5066512688', null, true, '2018-08-09');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('kstollmeier1', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'glunn1@newyorker.com', '7267344912', null, false, '2018-12-20');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('bbarg2', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'cturner2@usatoday.com', '8288653181', null, true, '2018-10-02');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('cmallock3', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'bkeasey3@europa.eu', '6769109678', null, false, '2018-09-25');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('amcduffy4', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'ocapitano4@springer.com', '8099658999', null, true, '2018-12-09');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('ncolbran5', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'volennachain5@lulu.com', '4977455075', null, false, '2018-09-23');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('mstebles6', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'aissacof6@nih.gov', '2111984543', null, false, '2018-09-26');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('rcuzen7', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'afurby7@yale.edu', '2877201380', null, true, '2018-08-21');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('kbrinkley8', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'astockings8@xinhuanet.com', '6301410308', null, false, '2018-09-01');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('lheggie9', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'jfinnigan9@i2i.jp', '4461166030', null, false, '2019-02-12');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('nwallegea', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'zthyinga@discuz.net', '2645882954', null, true, '2018-08-22');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('mmundeeb', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'pzambonb@reverbnation.com', '1431589105', null, false, '2018-09-05');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('jtrahearc', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'cminghettic@webnode.com', '5927917825', null, false, '2018-11-23');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('locurrigand', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'eswedelandd@weebly.com', '2221630447', null, false, '2019-01-13');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('zrowbothame', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'asnawdone@tuttocitta.it', '7551750078', null, true, '2018-09-28');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('hcreykef', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'mstichallf@gmpg.org', '4871917729', null, false, '2018-10-06');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('cmartinieg', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'gholtg@tinypic.com', '4308043814', null, false, '2018-08-18');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('hiornsh', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'pfanshaweh@nbcnews.com', '5375746124', null, false, '2019-01-09');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('mattwelli', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'hkembreyi@instagram.com', '2362071272', null, false, '2018-09-09');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('cmulroyj', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'swellingj@tinypic.com', '5132776191', null, true, '2018-10-24');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('ekirkamk', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'sstortonk@deliciousdays.com', '6352053761', null, false, '2018-12-06');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('mpopescul', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'zwiltsherl@webmd.com', '2554745062', null, false, '2018-08-12');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('scaghanm', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'mkernerm@kickstarter.com', '9189304771', null, false, '2018-11-27');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('erigollen', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'szellnern@paginegialle.it', '4655383946', null, false, '2019-02-03');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('tbagenalo', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'ecustardo@reddit.com', '8917349055', null, false, '2018-12-09');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('agennrichp', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'adanilevichp@blogger.com', '8269890096', null, true, '2018-10-20');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('ssmallboneq', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'ijeanneauq@webs.com', '9765029944', null, true, '2018-08-25');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('ccourteser', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'ayerrallr@360.cn', '4619726184', null, true, '2018-10-09');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('bscreachs', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'rspeers@apache.org', '1077983994', null, true, '2018-11-01');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('fcasserlyt', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'ncrowestt@cnet.com', '1047194135', null, false, '2018-11-02');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('cpeacheyu', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'mrickeardu@noaa.gov', '2964053052', null, false, '2018-08-10');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('bvickerstaffv', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'chucksteppv@smugmug.com', '6603572844', null, false, '2019-01-04');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('lwalterw', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'oclemensonw@sina.com.cn', '7547834271', null, false, '2018-10-21');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('jstopperx', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'jcammishx@wikia.com', '3543911762', null, false, '2018-10-22');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('smaruskay', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'goelsy@mapy.cz', '8022392180', null, false, '2019-01-11');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('rdutnellz', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'cpiattoz@xing.com', '9617914965', null, false, '2018-11-23');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('jcrowcher10', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'thordell10@wp.com', '3516854965', null, false, '2019-01-20');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('cgalilee11', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'elewty11@typepad.com', '8965599290', null, false, '2018-11-18');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('kpiff12', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'kmusson12@fc2.com', '8711806461', null, true, '2018-11-06');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('snajera13', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'kjanu13@ucoz.com', '8019437846', null, false, '2018-09-07');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('wdodwell14', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'jtrammel14@examiner.com', '9265862246', null, true, '2018-08-05');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('dscholz15', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'acafferky15@w3.org', '6677191417', null, true, '2018-10-15');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('rtiesman16', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'gyelyashev16@smh.com.au', '5175841597', null, true, '2018-12-29');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('obende17', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'tcollin17@hubpages.com', '4168158332', null, true, '2018-12-02');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('cpetruk18', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'sbradnick18@miibeian.gov.cn', '8225224044', null, false, '2018-10-25');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('wpaternoster19', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'ldespenser19@google.com.hk', '5862972063', null, false, '2018-11-25');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('jfosdick1a', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'fgryglewski1a@walmart.com', '4615099881', null, false, '2018-11-06');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('pbenezet1b', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'mbeggi1b@ehow.com', '7171222128', null, true, '2019-02-13');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('gkerridge1c', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'mreis1c@bbc.co.uk', '3614491455', null, true, '2018-08-25');
insert into USER_A (USER_NAME, USER_PASSWORD, USER_EMAIL, USER_TELEPHONE, USER_TOKEN, USER_ACTIVATED, USER_CREATED) values ('docahsedy1d', '055228cb4b2aafd8f4127ede8d8a7cef9a36ea0a', 'mjenicek1d@princeton.edu', '5244218170', null, true, '2018-08-22');

insert into ROLE_A (ROLE_NAME) values ('ROLE_ADMIN');
insert into ROLE_A (ROLE_NAME) values ('ROLE_USER');
insert into ROLE_A (ROLE_NAME) values ('ROLE_CARRIER');
insert into ROLE_A (ROLE_NAME) values ('ROLE_APPROVER');

insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (1,1);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (1, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (2, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (3, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (4, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (5, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (6, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (7, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (8, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (9, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (10, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (11, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (12, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (13, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (14, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (15, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (16, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (17, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (18, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (19, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (20, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (21, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (22, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (23, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (24, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (25, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (26, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (27, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (28, 2);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (29, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (30, 3);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (1, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (2, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (3, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (4, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (5, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (6, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (7, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (8, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (9, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (10, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (11, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (12, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (13, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (14, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (15, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (16, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (17, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (18, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (19, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (20, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (21, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (22, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (23, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (24, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (25, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (26, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (27, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (28, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (29, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (30, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (31, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (32, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (33, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (34, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (35, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (36, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (37, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (38, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (39, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (40, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (41, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (42, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (43, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (44, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (45, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (46, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (47, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (48, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (49, 4);
insert into ASSIGNED_ROLE (USER_ID, ROLE_ID) values (50, 4);


insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (31, 30);
insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (32, 24);
insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (50, 30);
insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (32, 30);
insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (42, 11);
insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (42, 16);
insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (42, 17);
insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (42, 18);
insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (42, 19);
insert into SUBSCRIPTION (USER_ID, CARRIER_ID) values (42, 20);

insert into PLANET (PLANET_NAME) values ('EARTH');
insert into PLANET (PLANET_NAME) values ('MOON');
insert into PLANET (PLANET_NAME) values ('VENUS');
insert into PLANET (PLANET_NAME) values ('MARS');
insert into PLANET (PLANET_NAME) values ('NIBIRU');

insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('laoreet', '2017-07-06', 5);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('elementum', '2017-10-04', 4);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('erat', '2017-05-04', 3);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('sapien', '2018-12-22', 3);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('lacus', '2018-05-21', 4);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('placerat', '2018-12-31', 1);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('vulputate', '2019-03-03', 1);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('a', '2018-05-13', 3);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('neque', '2019-02-01', 1);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('sed', '2017-09-26', 1);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('at', '2018-09-03', 1);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('egestas', '2017-05-25', 4);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('sem', '2017-12-19', 5);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('tellus', '2018-07-01', 4);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('vel', '2019-01-10', 5);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('convallis', '2018-12-24', 1);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('libero', '2019-02-17', 4);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('turpis', '2019-03-12', 2);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('porta', '2018-05-10', 2);
insert into SPACEPORT (SPACEPORT_NAME, CREATION_DATE, PLANET_ID) values ('sapien', '2017-09-23', 5);

insert into DISCOUNT (START_DATE, FINISH_DATE, DISCOUNT_RATE, IS_PERCENT) values ('2014-10-14', '2019-02-03', 14, true);
insert into DISCOUNT (START_DATE, FINISH_DATE, DISCOUNT_RATE, IS_PERCENT) values ('2014-09-11', '2019-04-16', 12, true);
insert into DISCOUNT (START_DATE, FINISH_DATE, DISCOUNT_RATE, IS_PERCENT) values ('2014-07-20', '2019-04-19', 79, false);
insert into DISCOUNT (START_DATE, FINISH_DATE, DISCOUNT_RATE, IS_PERCENT) values ('2018-06-17', '2019-03-06', 19, true);

insert into TRIP (CARRIER_ID, TRIP_STATUS, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_ID, ARRIVAL_ID, TRIP_PHOTO, APPROVER_ID, CREATION_DATE, TRIP_VIEWS) values (5, 1, '2016-02-12 01:39:20', '2016-07-16 09:43:44', 19, 9, 'MorbiOdio.jpeg', null, '2015-06-29 09:17:07', null);
insert into TRIP (CARRIER_ID, TRIP_STATUS, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_ID, ARRIVAL_ID, TRIP_PHOTO, APPROVER_ID, CREATION_DATE, TRIP_VIEWS) values (5, 2, '2016-05-14 16:57:24', '2016-12-24 06:26:08', 14, 19, 'EleifendQuamA.gif', null, '2015-01-19 01:07:47', null);
insert into TRIP (CARRIER_ID, TRIP_STATUS, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_ID, ARRIVAL_ID, TRIP_PHOTO, APPROVER_ID, CREATION_DATE, TRIP_VIEWS) values (7, 3, '2016-01-26 15:31:53', '2016-07-14 07:23:58', 17, 9, 'Justo.tiff', 3, '2015-04-04 16:21:20', null);
insert into TRIP (CARRIER_ID, TRIP_STATUS, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_ID, ARRIVAL_ID, TRIP_PHOTO, APPROVER_ID, CREATION_DATE, TRIP_VIEWS) values (7, 4, '2016-05-30 03:22:45', '2016-09-12 10:23:49', 19, 13, 'EnimBlanditMi.gif', 3, '2015-11-22 00:45:05', 57);
insert into TRIP (CARRIER_ID, TRIP_STATUS, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_ID, ARRIVAL_ID, TRIP_PHOTO, APPROVER_ID, CREATION_DATE, TRIP_VIEWS) values (6, 5, '2016-06-12 18:35:41', '2016-11-05 00:46:51', 14, 8, 'NecDui.jpeg', 4, '2015-01-07 13:42:37', 49);
insert into TRIP (CARRIER_ID, TRIP_STATUS, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_ID, ARRIVAL_ID, TRIP_PHOTO, APPROVER_ID, CREATION_DATE, TRIP_VIEWS) values (7, 6, '2016-06-22 13:10:36', '2016-07-21 07:19:15', 15, 3, 'Metus.gif', 1, '2015-02-17 20:41:12', 69);
insert into TRIP (CARRIER_ID, TRIP_STATUS, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_ID, ARRIVAL_ID, TRIP_PHOTO, APPROVER_ID, CREATION_DATE, TRIP_VIEWS) values (5, 7, '2016-02-22 14:57:36', '2016-11-21 17:59:10', 10, 20, 'Turpis.gif', 3, '2015-08-09 06:31:50', 8);

insert into TICKET_CLASS (CLASS_NAME, TRIP_ID, CLASS_SEATS, DISCOUNT_ID, TICKET_PRICE) values ('eget vulputate', 4, 11, null, 1984);
insert into TICKET_CLASS (CLASS_NAME, TRIP_ID, CLASS_SEATS, DISCOUNT_ID, TICKET_PRICE) values ('non sodales', 4, 20, null, 2531);
insert into TICKET_CLASS (CLASS_NAME, TRIP_ID, CLASS_SEATS, DISCOUNT_ID, TICKET_PRICE) values ('lacinia', 4, 14, 1, 3906);
insert into TICKET_CLASS (CLASS_NAME, TRIP_ID, CLASS_SEATS, DISCOUNT_ID, TICKET_PRICE) values ('eget vulputate-1', 1, 11, null, 1984);
insert into TICKET_CLASS (CLASS_NAME, TRIP_ID, CLASS_SEATS, DISCOUNT_ID, TICKET_PRICE) values ('eget vulputate-2', 2, 11, null, 1984);
insert into TICKET_CLASS (CLASS_NAME, TRIP_ID, CLASS_SEATS, DISCOUNT_ID, TICKET_PRICE) values ('eget vulputate-3', 3, 11, null, 1984);
insert into TICKET_CLASS (CLASS_NAME, TRIP_ID, CLASS_SEATS, DISCOUNT_ID, TICKET_PRICE) values ('eget vulputate-5', 5, 11, null, 1984);
insert into TICKET_CLASS (CLASS_NAME, TRIP_ID, CLASS_SEATS, DISCOUNT_ID, TICKET_PRICE) values ('eget vulputate-6', 6, 11, null, 1984);
insert into TICKET_CLASS (CLASS_NAME, TRIP_ID, CLASS_SEATS, DISCOUNT_ID, TICKET_PRICE) values ('eget vulputate-7', 7, 11, null, 1984);



insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, null, 1, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, null, 2, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, null, 3, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, 13, 4, 2335, '2016-02-27 19:14:19');
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, null, 5, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, null, 6, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, null, 7, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, 16, 8, 2335, '2016-02-20 02:02:09');
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, null, 9, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, null, 10, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (1, null, 11, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 12, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 13, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 14, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, 10, 15, 3201.56, '2015-12-20 03:26:08');
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 16, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, 18, 17, 3201.56, '2015-12-25 11:07:15');
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, 20, 18, 3201.56, '2016-03-14 08:30:14');
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 19, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 20, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 21, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 22, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 23, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 24, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 25, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 26, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, 11, 27, 2808, '2016-02-26 20:43:44');
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 28, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 29, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 30, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (2, null, 31, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 32, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 33, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 34, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 35, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 36, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 37, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 38, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 39, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 40, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 41, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 42, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 43, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 44, null, null);
insert into TICKET (CLASS_ID, PASSENGER_ID, SEAT, END_PRICE, PURCHASE_DATE) values (3, null, 45, null, null);

insert into SERVICE (CARRIER_ID, APPROVER_ID, SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_STATUS, CREATION_DATE, SERVICE_VIEWS) values (7, null, 'lobortis est phasellus', 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique', 1, '2015-03-23 21:49:14', null);
insert into SERVICE (CARRIER_ID, APPROVER_ID, SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_STATUS, CREATION_DATE, SERVICE_VIEWS) values (7, null, 'quis turpis eget', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt', 2, '2015-11-16 17:27:12', null);
insert into SERVICE (CARRIER_ID, APPROVER_ID, SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_STATUS, CREATION_DATE, SERVICE_VIEWS) values (7, 3, 'lacinia sapien quis libero', 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 3, '2015-11-09 17:06:54', null);
insert into SERVICE (CARRIER_ID, APPROVER_ID, SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_STATUS, CREATION_DATE, SERVICE_VIEWS) values (7, 2, 'ligula nec sem duis', 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', 4, '2015-05-03 01:15:06', 1000);
insert into SERVICE (CARRIER_ID, APPROVER_ID, SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_STATUS, CREATION_DATE, SERVICE_VIEWS) values (7, 2, 'ligula nec sem duis -2', 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla -2', 4, '2015-05-03 01:15:06', 1001);
insert into SERVICE (CARRIER_ID, APPROVER_ID, SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_STATUS, CREATION_DATE, SERVICE_VIEWS) values (7, 3, 'blandit mi', 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque', 5, '2015-02-13 05:41:17', 43);
insert into SERVICE (CARRIER_ID, APPROVER_ID, SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_STATUS, CREATION_DATE, SERVICE_VIEWS) values (7, 1, 'nullam porttitor lacus', 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', 6, '2015-05-05 07:03:57', 48);
insert into SERVICE (CARRIER_ID, APPROVER_ID, SERVICE_NAME, SERVICE_DESCRIPTION, SERVICE_STATUS, CREATION_DATE, SERVICE_VIEWS) values (7, 4, 'quis orci nullam', 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere', 7, '2015-07-29 18:56:38', 54);

insert into POSSIBLE_SERVICE (CLASS_ID, SERVICE_ID, SERVICE_PRICE) values (1, 4, 251);
insert into POSSIBLE_SERVICE (CLASS_ID, SERVICE_ID, SERVICE_PRICE) values (2, 4, 356);
insert into POSSIBLE_SERVICE (CLASS_ID, SERVICE_ID, SERVICE_PRICE) values (2, 5, 406);
insert into POSSIBLE_SERVICE (CLASS_ID, SERVICE_ID, SERVICE_PRICE) values (3, 4, 417);
insert into POSSIBLE_SERVICE (CLASS_ID, SERVICE_ID, SERVICE_PRICE) values (3, 5, 475);

insert into BOUGHT_SERVICE (TICKET_ID, P_SERVICE_ID) values (4, 1);
insert into BOUGHT_SERVICE (TICKET_ID, P_SERVICE_ID) values (8, 1);
insert into BOUGHT_SERVICE (TICKET_ID, P_SERVICE_ID) values (15, 2);
insert into BOUGHT_SERVICE (TICKET_ID, P_SERVICE_ID) values (15, 3);
insert into BOUGHT_SERVICE (TICKET_ID, P_SERVICE_ID) values (17, 2);
insert into BOUGHT_SERVICE (TICKET_ID, P_SERVICE_ID) values (17, 3);
insert into BOUGHT_SERVICE (TICKET_ID, P_SERVICE_ID) values (18, 2);
insert into BOUGHT_SERVICE (TICKET_ID, P_SERVICE_ID) values (18, 3);
insert into BOUGHT_SERVICE (TICKET_ID, P_SERVICE_ID) values (27, 2);

insert into SUGGESTION (CLASS_ID, DISCOUNT_ID) values (2, 2);
insert into SUGGESTION (CLASS_ID, DISCOUNT_ID) values (2, 3);

insert into SUGGESTED_SERVICE (SUGGESTION_ID, P_SERVICE_ID) values (1, 2);
insert into SUGGESTED_SERVICE (SUGGESTION_ID, P_SERVICE_ID) values (2, 2);
insert into SUGGESTED_SERVICE (SUGGESTION_ID, P_SERVICE_ID) values (2, 3);

insert into BUNDLE (START_DATE, FINISH_DATE, BUNDLE_PRICE, BUNDLE_DESCRIPTION, BUNDLE_PHOTO) values ('2015-08-15', '2016-04-15', 1488, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 'Semper.jpeg');
insert into BUNDLE (START_DATE, FINISH_DATE, BUNDLE_PRICE, BUNDLE_DESCRIPTION, BUNDLE_PHOTO) values ('2015-11-20', '2016-04-29', 9001, 'libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 'Eu.tiff');

insert into BUNDLE_CLASS (BUNDLE_ID, CLASS_ID, ITEM_NUMBER) values (1, 1, 1);
insert into BUNDLE_CLASS (BUNDLE_ID, CLASS_ID, ITEM_NUMBER) values (1, 2, 1);
insert into BUNDLE_CLASS (BUNDLE_ID, CLASS_ID, ITEM_NUMBER) values (2, 1, 3);

insert into BUNDLE_SERVICE (BUNDLE_ID, P_SERVICE_ID, ITEM_NUMBER) values (2, 2, 3);
insert into BUNDLE_SERVICE (BUNDLE_ID, P_SERVICE_ID, ITEM_NUMBER) values (1, 1, 1);
insert into BUNDLE_SERVICE (BUNDLE_ID, P_SERVICE_ID, ITEM_NUMBER) values (1, 2, 1);

insert into SCHEDULE (TRIP_ID, START_DATE, FINISH_DATE, INTERVAL, CREATION_DATE) values (4, '2014-08-03', '2020-08-03', 365, '2014-08-02');

insert into REPORT (REPORTER_ID, APPROVER_ID, TRIP_ID, STATUS, REPORT_RATE, REPORT_TEXT, CREATION_DATE) values (15, null, 7, 1, null, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', '2018-12-09');
insert into REPORT (REPORTER_ID, APPROVER_ID, TRIP_ID, STATUS, REPORT_RATE, REPORT_TEXT, CREATION_DATE) values (35, 2, 7, 2, null, 'amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo', '2019-01-25');
insert into REPORT (REPORTER_ID, APPROVER_ID, TRIP_ID, STATUS, REPORT_RATE, REPORT_TEXT, CREATION_DATE) values (36, 2, 6, 3, null, 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh', '2018-12-28');
insert into REPORT (REPORTER_ID, APPROVER_ID, TRIP_ID, STATUS, REPORT_RATE, REPORT_TEXT, CREATION_DATE) values (20, 3, 6, 4, null, 'eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt', '2019-01-19');
insert into REPORT (REPORTER_ID, APPROVER_ID, TRIP_ID, STATUS, REPORT_RATE, REPORT_TEXT, CREATION_DATE) values (21, 3, 6, 5, 1, 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque', '2019-02-20');
insert into REPORT (REPORTER_ID, APPROVER_ID, TRIP_ID, STATUS, REPORT_RATE, REPORT_TEXT, CREATION_DATE) values (38, 4, 6, 6, null, 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', '2019-02-03');

insert into REPORT_REPLY (REPORT_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (6, 12, 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', '2019-03-12');
insert into REPORT_REPLY (REPORT_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (3, 13, 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', '2018-12-29');
insert into REPORT_REPLY (REPORT_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (3, 2, 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', '2018-12-30');
insert into REPORT_REPLY (REPORT_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (2, 1, 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', '2019-02-25');
insert into REPORT_REPLY (REPORT_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (3, 3, 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', '2018-12-31');
insert into REPORT_REPLY (REPORT_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (5, 7, 'felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis', '2019-12-18');
insert into REPORT_REPLY (REPORT_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (5, 3, 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci', '2019-12-17');
insert into REPORT_REPLY (REPORT_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (3, 11, 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', '2019-01-28');

insert into FEEDBACK (REPORTER_ID, APPROVER_ID, TRIP_ID, STATUS, FEEDBACK_RATE, FEEDBACK_TEXT, CREATION_DATE) values (44, null, 7, 1, 2, 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat', '2019-01-17');
insert into FEEDBACK (REPORTER_ID, APPROVER_ID, TRIP_ID, STATUS, FEEDBACK_RATE, FEEDBACK_TEXT, CREATION_DATE) values (32, 3, 6, 2, 10, 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi', '2019-01-15');
insert into FEEDBACK (REPORTER_ID, APPROVER_ID, TRIP_ID, STATUS, FEEDBACK_RATE, FEEDBACK_TEXT, CREATION_DATE) values (19, 4, 5, 3, 10, 'purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut', '2019-01-29');

insert into TRIP_REPLY (TRIP_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (6, 2, 'accumsan felis ut at dolor quis odio', '2018-05-22 20:23:52');
insert into TRIP_REPLY (TRIP_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (5, 3, 'sapien cum sociis natoque penatibus et', '2019-01-13 05:19:44');
insert into TRIP_REPLY (TRIP_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (5, 3, 'vitae quam suspendisse potenti nullam porttitor lacus at', '2019-11-24 13:02:37');

insert into SERVICE_REPLY (SERVICE_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (6, 2, 'accumsan felis ut at dolor quis odio', '2018-05-22 20:23:52');
insert into SERVICE_REPLY (SERVICE_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (6, 3, 'sapien cum sociis natoque penatibus et', '2019-01-13 05:19:44');
insert into SERVICE_REPLY (SERVICE_ID, WRITER_ID, REPLY_TEXT, CREATION_DATE) values (6, 3, 'vitae quam suspendisse potenti nullam porttitor lacus at', '2019-11-24 13:02:37');
